[[keyboard.bindings]]
chars = "\u0002,"
key = "Comma"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002s"
key = "K"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00021"
key = "Key1"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00022"
key = "Key2"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00023"
key = "Key3"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00024"
key = "Key4"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00025"
key = "Key5"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00026"
key = "Key6"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00027"
key = "Key7"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00028"
key = "Key8"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00029"
key = "Key9"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002L"
key = "L"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002["
key = "LBracket"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002p"
key = "LBracket"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0002|"
key = "N"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0002-"
key = "N"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002d"
key = "D"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002n"
key = "RBracket"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = """
\u001B:w
"""
key = "S"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002c"
key = "T"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002!"
key = "T"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0002x"
key = "W"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002z"
key = "Z"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002/"
key = "F"
mods = "Command"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "Return"
mods = "Command"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Command"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Command"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Command"

[general]
import = ["~/.config/alacritty/themes/minimal-dark.toml"]

[cursor]
blink_interval = 210
blink_timeout = 0
unfocused_hollow = true
vi_mode_style = "None"

[cursor.style]
blinking = "Always"
shape = "Block"

[font]
size = 13.0

[font.bold]
family = "CaskaydiaCove Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "CaskaydiaCove Nerd Font Mono"
style = "Bold Italic"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "CaskaydiaCove Nerd Font Mono"
style = "Italic"

[font.normal]
family = "CaskaydiaCove Nerd Font Mono"
style = "Regular"

[font.offset]
x = 0
y = 0

[scrolling]
history = 10000

[window]
decorations = "none"
opacity = 0.80
blur = true
dynamic_title = true
startup_mode = "Windowed"

[window.dimensions]
columns = 140
lines = 38

[window.padding]
x = 10
y = 10

[selection]
save_to_clipboard = false

[mouse]
hide_when_typing = true

[keyboard]
