[[keyboard.bindings]]
chars = "\u0001,"
key = "Comma"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0001s"
key = "K"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00011"
key = "Key1"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00012"
key = "Key2"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00013"
key = "Key3"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00014"
key = "Key4"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00015"
key = "Key5"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00016"
key = "Key6"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00017"
key = "Key7"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00018"
key = "Key8"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00019"
key = "Key9"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0001L"
key = "L"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0001["
key = "LBracket"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0001p"
key = "LBracket"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0001|"
key = "N"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0001-"
key = "N"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0001d"
key = "D"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0001n"
key = "RBracket"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = """
\u001B:w
"""
key = "S"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0001c"
key = "T"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0001!"
key = "T"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0001x"
key = "W"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0001z"
key = "Z"
mods = "Command"

[general]
import = ["~/.config/alacritty/themes/minimal-dark.toml"]

[cursor]
blink_interval = 210
blink_timeout = 0
unfocused_hollow = true
vi_mode_style = "None"

[cursor.style]
blinking = "Always"
shape = "Block"

[font]
size = 13.0

[font.bold]
family = "CaskaydiaCove Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "CaskaydiaCove Nerd Font Mono"
style = "Bold Italic"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "CaskaydiaCove Nerd Font Mono"
style = "Italic"

[font.normal]
family = "CaskaydiaCove Nerd Font Mono"
style = "Regular"

[font.offset]
x = 0
y = 0

[scrolling]
history = 10000

[window]
decorations = "none"
opacity = 0.80
blur = true
dynamic_title = true
startup_mode = "Windowed"

[window.dimensions]
columns = 140
lines = 38

[window.padding]
x = 10
y = 10

[keyboard]
