# Minimal Dark Theme for Alacritty

[colors.bright]
black = "#555555"
blue = "#81a1c1"
cyan = "#8fbcbb"
green = "#a3be8c"
magenta = "#b48ead"
red = "#bf616a"
white = "#e5e9f0"
yellow = "#ebcb8b"

[colors.cursor]
cursor = "#61afef"
text = "#000000"

[colors.normal]
black = "#000000"
blue = "#5e81ac"
cyan = "#88c0d0"
green = "#a3be8c"
magenta = "#b48ead"
red = "#bf616a"
white = "#e5e9f0"
yellow = "#ebcb8b"

[colors.primary]
background = "#000000"
foreground = "#d8dee9"

# Selection colors
[colors.selection]
background = "#3b4252"
text = "#d8dee9"

[colors.search.matches]
background = "#88c0d0"
foreground = "#000000" 
